version: "3"
services:
  proj:
    image: proj
    container_name: proj
    ports:
      - "3000:3000"
    depends_on:
      - proj-db
  proj-db:
    image: proj-db
    container_name: proj-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: horus
    ports:
      - "5432:5432"
